### ISSUE TITLE
Add Plugin to Drone Plugin Index

### ISSUE THREAD

**Issue by jacksgt** [ptman/drone-plugin-matrix#3]
Hi,

you should totally add this cool integration to the [drone-plugin-index repostiory](https://github.com/drone/drone-plugin-index) 👍 

Greetings
Jack

**Comment by ptman** [comment]
I think I should fix the secrets handling to be in line with the other plugins first. @tboerger said something about this, but it got lost in chat history.

**Comment by tboerger** [comment]
Secrets should be accepted as MATRIX_ env variables, this should be overwritten by the PLUGIN_ vars if they are present. It's up to you if you add it only for username and token or also for values like the homeserver

**Comment by tboerger** [comment]
When the structure is compliant to to the other plugins I'm also fine to transfer it to drone-plugins where I can add you as an additional maintainer

**Comment by jacksgt** [comment]
I agree with @tboerger , `username`, `password`, `roomid` and `accesstoken` should definitely be secrets, but while we're at it `homeserver` could also be a secret.

In any case, I think it's fine to use `https://matrix.org` as the default homeserver when the env var / secret is not specified, e.g.:

https://github.com/ptman/drone-plugin-matrix/blob/master/main.go#L14

```golang
homeServer := os.Getenv("PLUGIN_HOMESERVER")
if homeServer == "" {
    homeServer = "https://matrix.org"
}
```

**Comment by ptman** [comment]
https://github.com/ptman/drone-plugin-matrix/commit/f69a402322ea5d3661f5c8e3f84cc82350d8dfd4

**Comment by ptman** [comment]
@tboerger so does this count as structure being compliant?

**Comment by tboerger** [comment]
Not exactly to transfer it to the drone-plugins org, but makes sense to add it to the plugin index at https://github.com/drone/drone-plugin-index

**Comment by jacksgt** [comment]
As PR https://github.com/drone/drone-plugin-index/pull/79 has been closed and the docs are published at http://plugins.drone.io/ptman/drone-plugin-matrix/

Awesome!
